version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: mongodb://mongo:27017/spaiadb
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
 